### ISSUE TITLE
How to extract the boundaries and Gate probabilities for an input wav file 

### ISSUE THREAD

**Issue by mohd-alhussin** [allyoushawn/timit_gas#1]
I am trying to apply this algorithm https://github.com/gary083/GAN_Harmonized_with_HMMs on the Libri-Speech data set and it requires unsupervised phone boundaries and they referred to your method. Your code doesn't output the boundaries for the input Wav files. I have modified your code to do so but I didn't get a good result and I am not sure how to validate the output I get from the code.

**Comment by allyoushawn** [comment]
Sorry I have missed the issue for such a long time lol. You are right, TIMIT dataset has phone boundaries labels while most of  other speech datasets do not provide such labels. To get phoneme boundaries, most people would turn to forced alignment approach. I also have a [kaldi-based forced alignment repo](https://github.com/allyoushawn/kaldi_forced_alignment) and you could give it a try if you are still interested.

**Comment by allyoushawn** [comment]
I am closing the issue since it has been a long time. Feel free to reach out again.
